#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "toy.ry".
#

require 'racc/parser'


module Toy

  class Parser < Racc::Parser

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 24, :_reduce_none,
 3, 24, :_reduce_none,
 3, 25, :_reduce_none,
 3, 25, :_reduce_none,
 3, 25, :_reduce_none,
 2, 25, :_reduce_none,
 1, 25, :_reduce_none,
 1, 26, :_reduce_none,
 1, 26, :_reduce_none,
 1, 27, :_reduce_none,
 3, 27, :_reduce_none,
 3, 27, :_reduce_none,
 3, 27, :_reduce_none,
 3, 27, :_reduce_none,
 3, 27, :_reduce_none,
 3, 27, :_reduce_none,
 2, 28, :_reduce_none,
 0, 30, :_reduce_none,
 3, 30, :_reduce_none,
 3, 30, :_reduce_none,
 2, 29, :_reduce_none,
 0, 32, :_reduce_none,
 3, 32, :_reduce_none,
 3, 32, :_reduce_none,
 3, 32, :_reduce_none,
 1, 31, :_reduce_none,
 1, 31, :_reduce_none,
 1, 31, :_reduce_none,
 1, 31, :_reduce_none ]

racc_reduce_n = 30

racc_shift_n = 56

racc_action_table = [
    29,    30,    29,    30,    29,    30,    29,    30,    25,    26,
    -6,    10,    46,    14,     2,     3,    31,    -6,    31,    -6,
    31,    18,    31,    11,    13,     1,    10,    35,    14,     2,
     3,    10,    17,    14,     2,     3,    25,    26,    11,    13,
     1,    25,    26,    11,    13,     1,    10,   nil,    14,     2,
     3,    10,   nil,    14,     2,     3,   nil,   nil,    11,    13,
     1,    -7,   nil,    11,    13,     1,   nil,   nil,    -7,   nil,
    -7,    19,    20,    21,    22,    23,    24,    19,    20,    21,
    22,    23,    24,    19,    20,    21,    22,    23,    24,    19,
    20,    21,    22,    23,    24,    19,    20,    21,    22,    23,
    24,    19,    20,    21,    22,    23,    24,    19,    20,    21,
    22,    23,    24,    11,    13,     1,    11,    13,     1,    11,
    13,     1,    11,    13,     1,    11,    13,     1,    11,    13,
     1,    11,    13,     1,    11,    13,     1,    11,    13,     1,
    11,    13,     1,    11,    13,     1,    11,    13,     1,    11,
    13,     1,    11,    13,     1 ]

racc_action_check = [
    49,    49,    48,    48,    47,    47,    12,    12,     9,     9,
    16,    33,    28,    33,    33,    33,    49,    16,    48,    16,
    47,     5,    12,    33,    33,    33,    18,    17,    18,    18,
    18,    15,     4,    15,    15,    15,    44,    44,    18,    18,
    18,    45,    45,    15,    15,    15,    10,   nil,    10,    10,
    10,     0,   nil,     0,     0,     0,   nil,   nil,    10,    10,
    10,     6,   nil,     0,     0,     0,   nil,   nil,     6,   nil,
     6,    38,    38,    38,    38,    38,    38,    40,    40,    40,
    40,    40,    40,     8,     8,     8,     8,     8,     8,    39,
    39,    39,    39,    39,    39,    42,    42,    42,    42,    42,
    42,    41,    41,    41,    41,    41,    41,    43,    43,    43,
    43,    43,    43,    24,    24,    24,     3,     3,     3,    22,
    22,    22,    25,    25,    25,    26,    26,    26,    21,    21,
    21,    20,    20,    20,    30,    30,    30,    31,    31,    31,
    19,    19,    19,     2,     2,     2,    14,    14,    14,    23,
    23,    23,    29,    29,    29 ]

racc_action_pointer = [
    43,   nil,   123,    96,    32,    14,    61,   nil,    70,     3,
    38,   nil,     3,   nil,   126,    23,    10,    27,    18,   120,
   111,   108,    99,   129,    93,   102,   105,   nil,     3,   132,
   114,   117,   nil,     3,   nil,   nil,   nil,   nil,    58,    76,
    64,    88,    82,    94,    31,    36,   nil,     1,    -1,    -3,
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -30,   -28,   -30,   -30,   -30,    -1,   -29,    -8,   -10,   -18,
   -30,   -26,   -22,   -27,   -30,   -29,   -29,   -30,   -30,   -30,
   -30,   -30,   -30,   -30,   -30,   -30,   -30,   -17,   -30,   -30,
   -30,   -30,   -21,   -29,    -5,    56,    -2,   -29,   -10,   -10,
   -10,   -10,   -10,   -10,   -18,   -18,    -3,   -22,   -22,   -22,
    -4,   -17,   -17,   -21,   -21,   -21 ]

racc_goto_table = [
    32,    34,     4,    27,    47,    48,    49,     6,   nil,    15,
    16,   nil,    28,    44,    45,   nil,   nil,     6,   nil,    50,
    36,    33,     6,   nil,   nil,     6,    38,    39,    40,    41,
    42,    43,   nil,   nil,   nil,    53,    54,    55,    51,    52,
     6 ]

racc_goto_check = [
     9,     2,     1,     7,     8,     8,     8,     3,   nil,     3,
     3,   nil,     1,     6,     6,   nil,   nil,     3,   nil,     2,
     1,     3,     3,   nil,   nil,     3,     5,     5,     5,     5,
     5,     5,   nil,   nil,   nil,     9,     9,     9,     7,     7,
     3 ]

racc_goto_pointer = [
   nil,     2,   -14,     7,   nil,     7,   -12,    -6,   -25,   -12 ]

racc_goto_default = [
   nil,   nil,     5,    37,     7,     8,     9,   nil,    12,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :UMINUS => 2,
 "*" => 3,
 "/" => 4,
 "+" => 5,
 "-" => 6,
 ";" => 7,
 "{" => 8,
 "}" => 9,
 "while" => 10,
 "if" => 11,
 "print" => 12,
 "==" => 13,
 "!=" => 14,
 ">" => 15,
 ">=" => 16,
 "<" => 17,
 "<=" => 18,
 "%" => 19,
 "read" => 20,
 :IDENT => 21,
 :NUMBER => 22 }

racc_use_result_var = true

racc_nt_base = 23

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'UMINUS',
'"*"',
'"/"',
'"+"',
'"-"',
'";"',
'"{"',
'"}"',
'"while"',
'"if"',
'"print"',
'"=="',
'"!="',
'">"',
'">="',
'"<"',
'"<="',
'"%"',
'"read"',
'IDENT',
'NUMBER',
'$start',
'prog',
'stat',
'asn',
'cmp',
'expr',
'term',
'expr1',
'fact',
'term1']

Racc_debug_parser = true

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

 # reduce 2 omitted

 # reduce 3 omitted

 # reduce 4 omitted

 # reduce 5 omitted

 # reduce 6 omitted

 # reduce 7 omitted

 # reduce 8 omitted

 # reduce 9 omitted

 # reduce 10 omitted

 # reduce 11 omitted

 # reduce 12 omitted

 # reduce 13 omitted

 # reduce 14 omitted

 # reduce 15 omitted

 # reduce 16 omitted

 # reduce 17 omitted

 # reduce 18 omitted

 # reduce 19 omitted

 # reduce 20 omitted

 # reduce 21 omitted

 # reduce 22 omitted

 # reduce 23 omitted

 # reduce 24 omitted

 # reduce 25 omitted

 # reduce 26 omitted

 # reduce 27 omitted

 # reduce 28 omitted

 # reduce 29 omitted

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module Toy
